# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=255)),
                ('variation', models.CharField(max_length=255)),
                ('completed', models.BooleanField(default=False)),
                ('ineligible', models.BooleanField(default=False)),
                ('installed', models.BooleanField(default=False)),
                ('left_study', models.BooleanField(default=False)),
                ('seen1', models.BooleanField(default=False)),
                ('seen2', models.BooleanField(default=False)),
                ('seen3', models.BooleanField(default=False)),
                ('seen7', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(default=b'')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'study',
                'verbose_name_plural': 'studies',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='studies.Study'),
        ),
    ]
